language: python

python:
  - 3.5

env:
  - DJANGO=Django==1.11.4

matrix:
  exclude:
    - python: 3.3
      env: DJANGO=Django==1.9.13
    - python: 3.3
      env: DJANGO=Django==1.10.7
    - python: 3.3
      env: DJANGO=Django==1.11.3

install:
  - pip install -q Django==$DJANGO_VERSION flake8 coverage

script:
#  - flake8
  - python manage.py test
  - coverage run --source=registration setup.py test

after_success:
  - coveralls --verbose
