language: python

python:
  - 3.5

env:
  - DJANGO=Django==1.11

install:
  - pip install -q Django==$DJANGO_VERSION flake8 coverage

script:
#  - flake8
  - python manage.py test
  - coverage run --source=registration setup.py test

after_success:
  - coveralls --verbose
