# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_app', '0003_auto_20171007_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_to',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
    ]
