# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin_app', '0004_auto_20171007_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproject',
            name='status',
            field=models.CharField(choices=[(0, 'not involved'), (1, 'in application'), (2, 'have joined'), (3, 'exited')], max_length=64, null=True),
        ),
    ]
